name: Xcode - Build and Analyze

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Update Xcode Version
        uses: JosephDuffy/update-xcode-version-action@v0.2.0
        with:
          # The path to a .yml file that describes which versions should be applied to which files.
          xcode-versions-file: .github/xcode-versions.yml
          # The path to search for Xcode versions in.
          xcode-search-path: /Applications
          # If provided will create a pull request with the changes.
          # github-token: # optional
          # If provided will generate a badge at the provided path.
          # xcode-version-badge-path: # optional
          # The version(s) to display in the generated badge. Provide multiple versions by separating with commas.
          # xcode-version-badge-versions: # optional, default is latest
          # 
          # quotes: # optional, default is double
          
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default | cat >default
          echo Using default scheme: $default
      - name: Build
        env:
          scheme: ${{ 'default' }}
        run: |
          if [ $scheme = default ]; then scheme=$(cat default); fi
          xcodebuild clean build analyze -scheme "$scheme"| xcpretty && exit ${PIPESTATUS[0]}
